### PR TITLE
sanitize trailing unicode fragments on truncation

### PR DESCRIPTION
**Pull request by matthewfala**
Signed-off-by: Matthew Fala <falamatt@amazon.com>

*Issue #, if available:*
https://github.com/aws/aws-for-fluent-bit/issues/252
*Description of changes:*
Please see issue for problem description.

## Solution Overview
The end of unicode character is determined when truncation is performed on logs. Logs are truncated between unicode characters rather than between a single unicode character's bytes.

The method is performed in the most efficient way possible. Many other solutions which could have been implemented  would have involved an O(n) scan of the logs to convert from bytes to runes in order to truncate unicode. This solution does O(1) as long as the log does not already contain corrupt unicode.

## Description
The solution takes advantage of the byte format of unicode characters:
https://en.wikipedia.org/wiki/UTF-8#History

Since a unicode character can be anywhere from 1 to 4 bytes, if we jump to a certain index to truncate around, it is not clear if we are at the start or in the middle of a unicode character.

Fortunately, unicode, utf-8 was designed so that all non-first unicode bytes begin with bits 10 so that scanning for the first unicode bit can be performed quickly. The solution scans backwards from the truncation byte to the point where the following byte is the start of the next unicode character (ie not 10xx xxxx).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by matthewfala** [comment]
Added go tests and also tested end to end via the following log payloads:
1 Unicode Fragment: https://tiny.amazon.com/ob1zb4oq/paste
2 Unicode Fragments: https://tiny.amazon.com/vkpv0bzd/paste

**Review by PettitWesley — APPROVED** [review]
👏 👏 For using the unicode spec to make this O(1) 👏 👏

**Review by zhonghui12 — APPROVED** [review]
Good job and thanks for the explanation👏

**Comment by zhonghui12** [comment]
Maybe you need to rebase the code before merging it.

**Pull request merged**
