### PR TITLE
Upgrade fluent-bit-go dependency to latest

### PR DESCRIPTION
**Pull request by dahu33**
Upgrade `fluent-bit-go to` latest as a fix for #164.

### CODE REVIEW

**Comment by dahu33** [comment]
@PettitWesley @DrewZhang13 would you mind having a look? It would be nice to have a working `aws-for-fluent-bit` docker image asap.

**Comment by PettitWesley** [comment]
Interesting, we have dependabot set up... I wonder why it never bumped this dependency

@hossain-rayhan

**Review by PettitWesley — APPROVED** [review]

**Comment by PettitWesley** [comment]
@hossain-rayhan Can you upgrade this dependency in the other plugins as well?

**Comment by hossain-rayhan** [comment]
> @hossain-rayhan Can you upgrade this dependency in the other plugins as well?

Yes. I am taking a look.

**Comment by hossain-rayhan** [comment]
> Interesting, we have dependabot set up... I wonder why it never bumped this dependency
> 
> @hossain-rayhan

I am not sure either. Need to have a look.

**Comment by hossain-rayhan** [comment]
> Interesting, we have dependabot set up... I wonder why it never bumped this dependency
> 
> @hossain-rayhan

Hey @PettitWesley, I think I found the root cause. We do not release/publish a tag for `fluent-bit-go` package. Hence, dependabot cannot track if a new release is available. It's not an issue with dependabot. Its more like a gap in the `fluent-bit-go` repo.

**Pull request merged**
